### ISSUE TITLE
add clang-format checker to the CI

### ISSUE THREAD

**Issue by mgerhold** [mgerhold/oopetris#75]

**Comment by Totto16** [comment]
I just wanted to ask on what type of clang-format (and also clang-tidy possibly?) I should implement.
As I already said before, it is possible to just check the files and report an error on the PR that it isn't correctly formatted
Or to reformat the files, if they aren't correct and then push these changes to the repo

**Comment by mgerhold** [comment]
I think the CI should only check if the code has been properly formatted and otherwise prevent merging. I don't want the CI to automatically create new commits.
If it's possible, we (read: you 🤓😂) could also include clang-tidy and/or cppcheck to the CI to get additional warnings. But I don't know if that is gonna work because maybe these tools will also analyze the dependencies and will issue warnings we cannot fix ourselves.

What do you think or prefer here?
